### ISSUE TITLE
No managed process in context

### ISSUE THREAD

**Issue by askogvold** [gridkit/nanocloud#12]
Hi

This looks like a really helpful library, which i could have good use for now.

However, when I check out the example project and try to run StartingWithDistributedCloud, I get:

    java.lang.IllegalArgumentException: No managed process in context
        at org.gridkit.nanocloud.telecontrol.ConsoleOutputSupport.check(ConsoleOutputSupport.java:147)
        at org.gridkit.nanocloud.telecontrol.ConsoleOutputSupport.ensureStreamMux(ConsoleOutputSupport.java:116)
        at org.gridkit.nanocloud.telecontrol.ConsoleOutputSupport.setEchoPrefix(ConsoleOutputSupport.java:101)
        at org.gridkit.nanocloud.telecontrol.ConsoleOutputSupport.set(ConsoleOutputSupport.java:65)
        at org.gridkit.vicluster.ViEngine$Core.applyPragmas(ViEngine.java:188)
        at org.gridkit.vicluster.ViEngine$Core.ignite(ViEngine.java:151)
        at org.gridkit.vicluster.telecontrol.jvm.ViEngineNodeProvider.createNode(ViEngineNodeProvider.java:29)
        at org.gridkit.vicluster.ViManager$ManagedNode.createNode(ViManager.java:559)
        at org.gridkit.vicluster.ViManager$ManagedNode.access$900(ViManager.java:298)
        at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:570)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    17:56:46.900 [ViNode[localhost] init] ERROR org.gridkit.vicluster.ViNodeSet - ViNode[localhost] initialization has failed
    java.lang.RuntimeException: Cannot create node, ManagedProcess is not available
        at org.gridkit.vicluster.telecontrol.jvm.ViEngineNode.<init>(ViEngineNode.java:51) ~[vicluster-core-0.8.10.jar:na]
        at org.gridkit.vicluster.telecontrol.jvm.ViEngineNodeProvider.createNode(ViEngineNodeProvider.java:30) ~[vicluster-core-0.8.10.jar:na]
        at org.gridkit.vicluster.ViManager$ManagedNode.createNode(ViManager.java:559) ~[vicluster-core-0.8.10.jar:na]
        at org.gridkit.vicluster.ViManager$ManagedNode.access$900(ViManager.java:298) ~[vicluster-core-0.8.10.jar:na]
        at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:570) ~[vicluster-core-0.8.10.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
    
    java.lang.RuntimeException: Cannot create node, ManagedProcess is not available
    
        at org.gridkit.vicluster.telecontrol.jvm.ViEngineNode.<init>(ViEngineNode.java:51)
        at org.gridkit.vicluster.telecontrol.jvm.ViEngineNodeProvider.createNode(ViEngineNodeProvider.java:30)
        at org.gridkit.vicluster.ViManager$ManagedNode.createNode(ViManager.java:559)
        at org.gridkit.vicluster.ViManager$ManagedNode.access$900(ViManager.java:298)
        at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:570)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:74

Changed the node reference to be 1 node called `localhost`.
Tested on RHEL5 through IntelliJ IDEA with JDK 1.8.0_25

**Comment by aragozin** [comment]
Have you checked [tutorial](https://github.com/gridkit/nanocloud/blob/vicluster-0.8/docs/NanoCloud_Tutorial.md)?

Usually requires some tweaking to work with your remote boxes.

Code assumes what you have boxes named cbox1 cbox2 cbox3 available.
I use hosts file to map few VMs to these name usually.

You may use same approach or change example to work with your host names.

Please also verify passwordless access ssh cbox1 should let you in without password. If you need password or anything please setup your [~/ssh-credentials.prop](https://github.com/gridkit/nanocloud/blob/vicluster-0.8/docs/NanoCloud_Configuring_SSH_credentials.md) file.

**Comment by askogvold** [comment]
Yes; verified passwordless ssh works in commandline (using id_rsa) Tried
both "localhost" and fqdn for the nodes.

tor. 4. feb. 2016, 19.32 skrev aragozin <notifications@github.com>:

**Comment by aragozin** [comment]
Indeed configuration defaults is broken in current version.
Please try following additional configuration

    cloud.node("localhost").x(RemoteNode.REMOTE).setRemoteAccount(System.getProperty("user.name"));
    cloud.node("localhost").x(RemoteNode.REMOTE).setSshPrivateKey("~/.ssh/id_rsa");

**Comment by aragozin** [comment]
Fixed in 0.8.11
Tutorial project is updated
