### ISSUE TITLE
Ssh password auth does not work as expected

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [gridkit/nanocloud#9]
When source code looks like in this demo [Алексей Рагозин — Сеть — это большая JVM](https://youtu.be/EcoJrYJczqc?t=2794) :
```java
ViNode node = cloud.node("mynode");
RemoteNode.at(node).setProp(RemoteNodeProps.ACCOUNT, "root");
RemoteNode.at(node).setProp(RemoteNodeProps.PASSWORD, "somepassword");
```
Or
```java
ViNode node = cloud.node("mynode");
RemoteNode.at(node).setRemoteAccount("root");
RemoteNode.at(node).setProp(RemoteNodeProps.PASSWORD, "somepassword");
```

Then SSH connection fails because password unresolved
```java
public class RemoteConsoleInitializer implements InductiveRule {
...
          String password = resolvePassword(game);  // returns null. why?
```
As result:
```
ERROR 21:02:04,570  [ViNode[master] init] ViNodeSet | ViNode[master] initialization has failed
java.lang.RuntimeException: org.gridkit.internal.com.jcraft.jsch.JSchException: Auth cancel
	at org.gridkit.nanocloud.telecontrol.ssh.RemoteConsoleInitializer$TunnelInitializer.getService(RemoteConsoleInitializer.java:175)
	at org.gridkit.nanocloud.telecontrol.ssh.RemoteConsoleInitializer$TunnelInitializer.getService(RemoteConsoleInitializer.java:130)
	at org.gridkit.vicluster.AbstractCloudContext.lookup(AbstractCloudContext.java:50)
	at org.gridkit.nanocloud.telecontrol.ssh.RemoteConsoleInitializer.initConsole(RemoteConsoleInitializer.java:57)
	at org.gridkit.nanocloud.telecontrol.ssh.RemoteConsoleInitializer.apply(RemoteConsoleInitializer.java:31)
	at org.gridkit.vicluster.ViEngine$InductiveRuleHook.rerun(ViEngine.java:773)
	at org.gridkit.vicluster.ViEngineGame.play(ViEngineGame.java:70)
	at org.gridkit.vicluster.ViEngine$Core.processPhase(ViEngine.java:270)
	at org.gridkit.vicluster.ViEngine$Core.ignite(ViEngine.java:131)
	at org.gridkit.vicluster.telecontrol.jvm.ViEngineNodeProvider.createNode(ViEngineNodeProvider.java:29)
	at org.gridkit.vicluster.ViManager$ManagedNode.createNode(ViManager.java:549)
	at org.gridkit.vicluster.ViManager$ManagedNode.access$900(ViManager.java:288)
	at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gridkit.internal.com.jcraft.jsch.JSchException: Auth cancel
	at org.gridkit.internal.com.jcraft.jsch.Session.connect(Session.java:487)
	at org.gridkit.internal.com.jcraft.jsch.Session.connect(Session.java:166)
	at org.gridkit.vicluster.telecontrol.ssh.SimpleSshSessionProvider.getSession(SimpleSshSessionProvider.java:112)
	at org.gridkit.nanocloud.telecontrol.ssh.RemoteConsoleInitializer$TunnelInitializer.getService(RemoteConsoleInitializer.java:173)
	... 17 more
```

When I use legacy deprecated way:
```java
ViNode node = cloud.node("master");
RemoteNode.at(node).setProp(RemoteNodeProps.ACCOUNT, "root");
RemoteNode.at(node).setPassword("somepassword");
node.touch();
```
Then SSH connection opens succesfully, all dependencies are copied to /tmp/nanocloud on remote machine, but following  error raised after dependency coping:
```
java.lang.IllegalArgumentException: No handler for pargma 'ssh:password' is found
	at org.gridkit.vicluster.ViEngine$Core.applyPragmas(ViEngine.java:185)
	at org.gridkit.vicluster.ViEngine$Core.ignite(ViEngine.java:151)
	at org.gridkit.vicluster.telecontrol.jvm.ViEngineNodeProvider.createNode(ViEngineNodeProvider.java:29)
	at org.gridkit.vicluster.ViManager$ManagedNode.createNode(ViManager.java:549)
	at org.gridkit.vicluster.ViManager$ManagedNode.access$900(ViManager.java:288)
	at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-10-24 20:58:02.469+0300 console - [WARN] 
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task org.gridkit.util.concurrent.AdvancedExecutorAdapter$2@18aff869 rejected from java.util.concurrent.ThreadPoolExecutor@40d7c659[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at org.gridkit.util.concurrent.AdvancedExecutorAdapter.execute(AdvancedExecutorAdapter.java:31)
	at org.gridkit.util.concurrent.AdvancedExecutorAdapter.submit(AdvancedExecutorAdapter.java:55)
	at org.gridkit.zerormi.RmiGateway$RemoteExecutionService.submit(RmiGateway.java:734)
	at org.gridkit.vicluster.AdvExecutor2ViExecutor.submit(AdvExecutor2ViExecutor.java:83)
	at org.gridkit.vicluster.AdvExecutor2ViExecutor.exec(AdvExecutor2ViExecutor.java:61)
	at org.gridkit.vicluster.telecontrol.jvm.ViEngineNode.exec(ViEngineNode.java:81)
	at org.gridkit.vicluster.ViManager$ManagedNode$InitTask.run(ViManager.java:569)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

If does matter then viconf file looks as following:
```
# Use remote node type by default
**: node:type=remote

# master
master.**: remote:host=sss01-p01-pjm01
master.**: jvm:exec-command=/usr/bin/java
master.**: remote-runtime:jar-cache=/tmp/nanocloud
```

**Comment by aragozin** [comment]
I do not see you using viconf file in code, so it is probably irrelevant.

Minimal configuration for remote node would look like

```
Cloud c = CloudFactory.createCloud();
c.node("**").x(RemoteNode.REMOTE).useSimpleRemoting();
        
c.node("**").x(RemoteNode.REMOTE).setRemoteAccount("root");
c.node("**").x(RemoteNode.REMOTE).setPassword("reverse");
        
c.node("cbox1").exec(new Runnable() {
...

**Comment by vladimir-bukhtoyarov** [comment]
Thanks for help, it works fine for me.
